name: Run

on:
  workflow_dispatch:
  repository_dispatch:
  schedule:
  # 定时任务，国际标准时间（北京时间+8）
      #每天的4点
    - cron: '0 20 * * *'
    - cron: '0 22 * * *'
    - cron: '0 0 * * *'
    - cron: '0 2 * * *'
    - cron: '0 4 * * *'
    - cron: '0 6 * * *'
    - cron: '0 8 * * *'
    - cron: '0 10 * * *'
    - cron: '0 12 * * *'
    - cron: '0 14 * * *'
    - cron: '0 16 * * *'
    - cron: '0 18 * * *'
    #新增
    - cron: '0 21 * * *'
    - cron: '0 23 * * *'
    - cron: '0 1 * * *'
    - cron: '0 3 * * *'
    - cron: '0 5 * * *'
    - cron: '0 7 * * *'
    - cron: '0 9 * * *'
    - cron: '0 11 * * *'
    - cron: '0 13 * * *'
    - cron: '0 15 * * *'
    - cron: '0 17 * * *'
    - cron: '0 19 * * *'

jobs:
  build:

    if: github.actor == github.repository_owner
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Run
      uses: coactions/setup-xvfb@main
      with:
        run: dotnet run
      env: 
        CONF: ${{ secrets.CONF }}
