name: Run

on:
  workflow_dispatch:
  repository_dispatch:
  schedule:
  # 定时任务，国际标准时间（北京时间+8）
      #每天的4点
    - cron: '0 20 * * *'
    - cron: '0 2 * * *'
    - cron: '0 8 * * *'
    - cron: '0 14 * * *'

jobs:
  build:

    if: github.actor == github.repository_owner
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Run
      uses: coactions/setup-xvfb@main
      with:
        run: dotnet run
      env: 
        CONF: ${{ secrets.CONF }}
